<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/src/bootstrap.php';
$store = cms_store_repository()->findPublishedBySlug((string) ($_GET['slug'] ?? ''));
$storeImages = $store === null ? [] : cms_store_repository()->images((int) $store['id']);
$reservationUrl = $store === null ? '' : str_replace('{store_slug}', rawurlencode((string) $store['slug']), (string) app_config()['reservation_url']);
if ($store === null) { http_response_code(404); }
?><!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= h($store['name'] ?? '店舗が見つかりません') ?> | プロ厨房HIT</title><link rel="stylesheet" href="assets/catalogue.css"></head><body>
<header class="site-header"><a class="brand" href="index.php"><small>厨房づくりと厨房機器</small><strong>プロ厨房HIT</strong></a></header><main class="detail-main"><nav class="breadcrumb"><a href="index.php">ホーム</a><span>›</span><a href="stores.php">店舗一覧</a></nav>
<?php if ($store === null): ?><section class="not-found"><h1>店舗が見つかりません</h1><p><a href="stores.php">店舗一覧へ戻る</a></p></section><?php else: ?><section class="product-detail"><div><div class="gallery"><?php foreach ($storeImages as $image): ?><img src="<?= h(public_url($image['file_path'])) ?>" alt="<?= h($image['alt_text']) ?>"><?php endforeach; ?><?php if ($storeImages === [] && $store['main_image'] !== ''): ?><img src="<?= h(public_url($store['main_image'])) ?>" alt="<?= h($store['name']) ?>"><?php endif; ?></div></div><div class="detail-copy"><p class="eyebrow">STORE</p><h1><?= h($store['name']) ?></h1><p><?= h($store['catchphrase']) ?></p><dl class="specs"><div><dt>住所</dt><dd>〒<?= h($store['postal_code']) ?><br><?= h($store['prefecture'].$store['city'].$store['address_line'].$store['building']) ?></dd></div><div><dt>電話</dt><dd><?= h($store['phone']) ?></dd></div><div><dt>営業時間</dt><dd><?= h($store['business_hours']) ?></dd></div><div><dt>定休日</dt><dd><?= h($store['holidays']) ?></dd></div></dl><div class="description"><h2>店舗について</h2><p><?= nl2br(h($store['description'])) ?></p></div><?php if ($store['accepts_reservations'] && $reservationUrl !== ''): ?><a class="button inquiry" href="<?= h($reservationUrl) ?>">来店予約を希望する</a><?php endif; ?></div></section><?php endif; ?></main><footer>株式会社アイリテクノ</footer></body></html>
